config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  devise_for :admins, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'segredo', confirmation: 'verificacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'entrar' }
  
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    resources :albums
    post 'fotos-album/', to: 'album_photos#create', as: 'album_photos'
    delete 'fotos-album/:id', to: 'album_photos#destroy', as: 'album_photo'
    resources :teammates, path: 'membros-da-equipe'
    resources :success_stories, path: 'historias-de-sucesso'
    resources :animals, path: 'bichos'
    post 'fotos-animal', to: 'animal_photos#create', as: 'animal_photos'
    delete 'fotos-animal/:id', to: 'animal_photos#destroy', as: 'animal_photo'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/success_story.rb
class SuccessStory < ApplicationRecord
end

app/controllers/success_stories_controller.rb
class SuccessStoriesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_success_story, only: [:show, :edit, :update, :destroy]

  # GET /success_stories
  # GET /success_stories.json
  def index
    @success_stories = SuccessStory.all
  end

  # GET /success_stories/1
  # GET /success_stories/1.json
  def show
  end

  # GET /success_stories/new
  def new
    @success_story = SuccessStory.new
  end

  # GET /success_stories/1/edit
  def edit
  end

  # POST /success_stories
  # POST /success_stories.json
  def create
    @success_story = SuccessStory.new(success_story_params)

    respond_to do |format|
      if @success_story.save
        format.html { redirect_to @success_story, notice: 'Success story was successfully created.' }
        format.json { render :show, status: :created, location: @success_story }
      else
        format.html { render :new }
        format.json { render json: @success_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /success_stories/1
  # PATCH/PUT /success_stories/1.json
  def update
    respond_to do |format|
      if @success_story.update(success_story_params)
        format.html { redirect_to @success_story, notice: 'Success story was successfully updated.' }
        format.json { render :show, status: :ok, location: @success_story }
      else
        format.html { render :edit }
        format.json { render json: @success_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /success_stories/1
  # DELETE /success_stories/1.json
  def destroy
    @success_story.destroy
    respond_to do |format|
      format.html { redirect_to success_stories_url, notice: 'Success story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_success_story
      @success_story = SuccessStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def success_story_params
      params.require(:success_story).permit(:pet_name, :owner, :photo, :description)
    end
end

app/helpers/success_stories_helper.rb
module SuccessStoriesHelper
end

app/views/success_stories/_form.html.erb
<%= form_with(model: success_story, local: true) do |form| %>
  <% if success_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(success_story.errors.count, "error") %> prohibited this success_story from being saved:</h2>

      <ul>
      <% success_story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pet_name %>
    <%= form.text_field :pet_name %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/success_stories/edit.html.erb
<h1>Editando História de Sucesso</h1>

<%= render 'form', success_story: @success_story %>

<%= link_to 'Exibir', @success_story %> |
<%= link_to 'Voltar', success_stories_path %>

app/views/success_stories/index.html.erb
<h1>Histórias de Sucesso</h1>

<table>
  <thead>
    <tr>
      <th>Nome do Bicho</th>
      <th>Dono</th>
      <th>Foto</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @success_stories.each do |success_story| %>
      <tr>
        <td><%= success_story.pet_name %></td>
        <td><%= success_story.owner %></td>
        <td><%= success_story.photo %></td>
        <td><%= success_story.description %></td>
        <td><%= link_to 'Exibir', success_story %></td>
        <td><%= link_to 'Editar', edit_success_story_path(success_story) %></td>
        <td><%= link_to 'Excluir', success_story, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova História de Sucesso', new_success_story_path %>

app/views/success_stories/new.html.erb
<h1>Nova História de Sucesso</h1>

<%= render 'form', success_story: @success_story %>

<%= link_to 'Voltar', success_stories_path %>

app/views/success_stories/show.html.erb
<p>
  <strong>Nome do Bicho:</strong>
  <%= @success_story.pet_name %>
</p>

<p>
  <strong>Dono:</strong>
  <%= @success_story.owner %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @success_story.photo %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @success_story.description %>
</p>

<%= link_to 'Editar', edit_success_story_path(@success_story) %> |
<%= link_to 'Voltar', success_stories_path %>