config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  devise_for :admins, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'segredo', confirmation: 'verificacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'entrar' }
  
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    resources :albums
    post 'fotos-album/', to: 'album_photos#create', as: 'album_photos'
    delete 'fotos-album/:id', to: 'album_photos#destroy', as: 'album_photo'
    resources :teammates, path: 'membros-da-equipe'
    resources :success_stories, path: 'historias-de-sucesso'
    resources :animals, path: 'bichos'
    post 'fotos-animal', to: 'animal_photos#create', as: 'animal_photos'
    delete 'fotos-animal/:id', to: 'animal_photos#destroy', as: 'animal_photo'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :animal_photos, dependent: :destroy
  
  enum sex: {female: false, male: true}
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal_photo = AnimalPhoto.new
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :birth, :sex, :description, :observations, :adopted, :owner, :phone, :mobile_phone, :email)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
    def human_sex(sex)
        hash = {male: 'Macho', female: 'Fêmea'}
        hash[sex.to_sym]
    end
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birth %>
    <%= form.date_select :birth %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.check_box :sex %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :observations %>
    <%= form.text_area :observations %>
  </div>

  <div class="field">
    <%= form.label :adopted %>
    <%= form.check_box :adopted %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :mobile_phone %>
    <%= form.text_field :mobile_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editando Bicho</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Exibir', @animal %> |
<%= link_to 'Voltar', animals_path %>

app/views/animals/index.html.erb
<h1>Bichos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nascimento</th>
      <th>Sexo</th>
      <th>Descrição</th>
      <th>Observações</th>
      <th>Adotado?</th>
      <th>Dono</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>E-mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= l animal.birth %></td>
        <td><%= human_sex(animal.sex) %></td>
        <td><%= animal.description %></td>
        <td><%= animal.observations %></td>
        <td><%= t animal.adopted %></td>
        <td><%= animal.owner %></td>
        <td><%= animal.phone %></td>
        <td><%= animal.mobile_phone %></td>
        <td><%= animal.email %></td>
        <td><%= link_to 'Exibir', animal %></td>
        <td><%= link_to 'Editar', edit_animal_path(animal) %></td>
        <td><%= link_to 'Excluir', animal, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>Novo Bicho</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= l @animal.birth %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= human_sex(@animal.sex) %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @animal.description %>
</p>

<p>
  <strong>Observações:</strong>
  <%= @animal.observations %>
</p>

<p>
  <strong>Adotado?</strong>
  <%= t @animal.adopted %>
</p>

<p>
  <strong>Dono:</strong>
  <%= @animal.owner %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @animal.phone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @animal.mobile_phone %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @animal.email %>
</p>

<div id='animal_photos'>
  <%= render @animal.animal_photos %>
</div>

<%= form_with(model: @animal_photo, id: 'new_animal_photo') do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.file_field :content %>
  </div>
  <%= form.hidden_field :animal_id, value: @animal.id %>
  <%= form.submit %>
<% end %>

<%= link_to 'Editar', edit_animal_path(@animal) %> |
<%= link_to 'Voltar', animals_path %>