config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  devise_for :admins, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'segredo', confirmation: 'verificacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'entrar' }
  
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    resources :albums
    post 'fotos-album/', to: 'album_photos#create', as: 'album_photos'
    delete 'fotos-album/:id', to: 'album_photos#destroy', as: 'album_photo'
    resources :teammates, path: 'membros-da-equipe'
    resources :success_stories, path: 'historias-de-sucesso'
    resources :animals, path: 'bichos'
    post 'fotos-animal', to: 'animal_photos#create', as: 'animal_photos'
    delete 'fotos-animal/:id', to: 'animal_photos#destroy', as: 'animal_photo'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teammate.rb
class Teammate < ApplicationRecord
end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_teammate, only: [:show, :edit, :update, :destroy]

  # GET /teammates
  # GET /teammates.json
  def index
    @teammates = Teammate.all
  end

  # GET /teammates/1
  # GET /teammates/1.json
  def show
  end

  # GET /teammates/new
  def new
    @teammate = Teammate.new
  end

  # GET /teammates/1/edit
  def edit
  end

  # POST /teammates
  # POST /teammates.json
  def create
    @teammate = Teammate.new(teammate_params)

    respond_to do |format|
      if @teammate.save
        format.html { redirect_to @teammate, notice: 'Teammate was successfully created.' }
        format.json { render :show, status: :created, location: @teammate }
      else
        format.html { render :new }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teammates/1
  # PATCH/PUT /teammates/1.json
  def update
    respond_to do |format|
      if @teammate.update(teammate_params)
        format.html { redirect_to @teammate, notice: 'Teammate was successfully updated.' }
        format.json { render :show, status: :ok, location: @teammate }
      else
        format.html { render :edit }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammates/1
  # DELETE /teammates/1.json
  def destroy
    @teammate.destroy
    respond_to do |format|
      format.html { redirect_to teammates_url, notice: 'Teammate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teammate
      @teammate = Teammate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teammate_params
      params.require(:teammate).permit(:name, :photo, :nickname, :description)
    end
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/teammates/_form.html.erb
<%= form_with(model: teammate, local: true) do |form| %>
  <% if teammate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teammate.errors.count, "error") %> prohibited this teammate from being saved:</h2>

      <ul>
      <% teammate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teammates/edit.html.erb
<h1>Editando Membro da Equipe</h1>

<%= render 'form', teammate: @teammate %>

<%= link_to 'Exibir', @teammate %> |
<%= link_to 'Voltar', teammates_path %>

app/views/teammates/index.html.erb
<h1>Membros da Equipe</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Foto</th>
      <th>Apelido</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teammates.each do |teammate| %>
      <tr>
        <td><%= teammate.name %></td>
        <td><%= teammate.photo %></td>
        <td><%= teammate.nickname %></td>
        <td><%= teammate.description %></td>
        <td><%= link_to 'Exibir', teammate %></td>
        <td><%= link_to 'Editar', edit_teammate_path(teammate) %></td>
        <td><%= link_to 'Excluir', teammate, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Membro da Equipe', new_teammate_path %>

app/views/teammates/new.html.erb
<h1>Novo Membro da Equipe</h1>

<%= render 'form', teammate: @teammate %>

<%= link_to 'Voltar', teammates_path %>

app/views/teammates/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @teammate.name %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @teammate.photo %>
</p>

<p>
  <strong>Apelido:</strong>
  <%= @teammate.nickname %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @teammate.description %>
</p>

<%= link_to 'Editar', edit_teammate_path(@teammate) %> |
<%= link_to 'Voltar', teammates_path %>