config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  devise_for :admins, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'segredo', confirmation: 'verificacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'entrar' }
  
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    resources :albums
    post 'fotos-album/', to: 'album_photos#create', as: 'album_photos'
    delete 'fotos-album/:id', to: 'album_photos#destroy', as: 'album_photo'
    resources :teammates, path: 'membros-da-equipe'
    resources :success_stories, path: 'historias-de-sucesso'
    resources :animals, path: 'bichos'
    post 'fotos-animal', to: 'animal_photos#create', as: 'animal_photos'
    delete 'fotos-animal/:id', to: 'animal_photos#destroy', as: 'animal_photo'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :album_photos, dependent: :destroy

    validates :name, presence: true, length: { maximum: 100 }

    mount_uploader :cover_photo, PhotoUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all.order(:date)
  end

  def show
    @photos = @album.album_photos
    @album_photo = AlbumPhoto.new
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album criado com sucesso.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def album_params
      params.require(:album).permit(:name, :description, :date, :cover_photo)
    end

    def set_album
      @album = Album.find(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<li>
    <div class='album'>
        <strong><%= album.name %></strong>
        <%= image_tag album.cover_photo.url if album.cover_photo.present? %>
        <p><%= album.description %></p>
        <%= button_to 'Ir ao Album', album, method: :get %>
    </div>
</li>

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2>Alguns erros impediram este Album de ser salvo:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :cover_photo %>
    <%= form.file_field :cover_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editando Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Exibir', @album %> |
<%= link_to 'Voltar', albums_path %>

app/views/albums/index.html.erb
<h1>Índice de Albums</h1>

<ul>
    <%= render @albums %>
</ul>

<%= link_to 'Novo Album', new_album_path %>

app/views/albums/new.html.erb
<h1>Novo Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Voltar', albums_path %>

app/views/albums/show.html.erb
<h1>Álbum: <%= @album.name %></h1>
<%= image_tag @album.cover_photo.url if @album.cover_photo.present? %>
<p><%= l @album.date %></p>

<h2>Fotos</h2>

<ul id='album_photos'>
    <%= render @photos %>
</ul>

<% if is_admin? %>
    <%= form_with(model: @album_photo, id: 'new_album_photo') do |form| %>
    <div class="field">
        <%= form.label :content %>
        <%= form.file_field :content %>
    </div>
    <%= form.hidden_field :album_id, value: @album.id %>
    <%= form.submit %>
    <% end %>

    <%= link_to 'Editar', edit_album_path(@album) %> |
<% end %>

<%= link_to 'Voltar', albums_path %>